#!/usr/bin/env bash
# Check if all 4 parameters are provided
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assign parameters to variables
file_path = "$1"
server_ip = "$2"
username  = "$3"
ssh_keys  = "$4"

# Check if the file exits
if [ ! -f "$file_path" ]; then
	echo "Error: File not found at $file_path"
	exit 1
fi

# Disable strict host key checking and transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
