#!/usr/bin/env bash
#task 9

echo "$$" > /var/run/myscript.pid

term() {
	rm -r /var/run/myscript.pid
	exit
}

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && term' SIGTERM
	trap 'terminator' SIGQUIT
done
