#!/usr/bin/env bash
#A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

a=10
while ((a))
do
	echo "Best School"
	if [ $a == 2 ]
	then
		echo "Hi"
	fi
	((a--))
done
