#!/usr/bin/env bash
#A Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

a = 1
while [ a <= 10 ]
do
	echo "Best School"
	if [ a == 8 ]
	do
		echo "hi"
	fi
	((a++))
done
